apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: example-com
  namespace: kuoss-dev
spec:
  dnsNames:
  - example.com
  - '*.example.com'
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: tls-example-com
