clone:
	git clone https://github.com/kuoss/lethe.git
	git clone https://github.com/kuoss/venti.git

pull:
	cd lethe && git pull
	cd venti && git pull

install:
	cd lethe && make install-dev
	cd venti && make install-dev

config:
	rm -f lethe/etc/lethe.yaml       && cd lethe/etc/ && ln -s ../../devpod/config/lethe.yaml       .
	rm -f venti/etc/datasources.yaml && cd venti/etc/ && ln -s ../../devpod/config/datasources.yaml .

run-lethe:
	cd lethe && make run-dev

run-venti:
	cd venti && make run-dev

run-venti-watch:
	cd venti && make run-watch
