clone:
	git clone -b develop https://github.com/kuoss/lethe.git
	git clone https://github.com/kuoss/venti.git

pull:
	cd lethe && git pull
	cd venti && git pull

install:
	cd lethe && make install-dev
	cd venti && make install-dev

config:
	cp devpod/config/lethe.yaml       lethe/etc/
	cp devpod/config/datasources.yaml venti/etc/

run-lethe:
	cd lethe && make run-dev

run-venti:
	cd venti && make run-dev

