clone:
	git clone https://github.com/kuoss/lethe.git
	git clone https://github.com/kuoss/venti.git

pull:
	cd lethe && git pull
	cd venti && git pull

install:
	cd lethe && make install-dev
	cd venti && make install-dev

config:
	rm -f lethe/etc/lethe.yaml       && ln -rs devpod/config/lethe.yaml       lethe/etc/
	rm -f venti/etc/datasources.yaml && ln -rs devpod/config/datasources.yaml venti/etc/

run-lethe:
	cd lethe && make run-dev

run-venti:
	cd venti && make run-dev

run-venti-watch:
	cd venti && make run-watch
