apiVersion: apps/v1
kind: Deployment
metadata:
  name: lethe
  namespace: kuoss
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: lethe
  template:
    metadata:
      labels:
        app: lethe
    spec:
      terminationGracePeriodSeconds: 0
      nodeSelector:
        kubernetes.io/os: linux
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values: ["devpod"]
            topologyKey: kubernetes.io/hostname
      containers:
      - name: writer
        image: fluent/fluent-bit:1.9.3
        volumeMounts:
        - name: vol-data
          mountPath: /data
        - name: vol-config
          mountPath: /fluent-bit/etc
      volumes:
      - name: vol-config
        configMap:
          name: lethe
      - name: vol-data
        persistentVolumeClaim:
          claimName: lethe