apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: devpod
  namespace: kuoss-dev
spec:
  serviceName: devpod
  selector:
    matchLabels:
      app: devpod
  template:
    metadata:
      labels:
        app: devpod
    spec:
      serviceAccountName: venti-dev
      terminationGracePeriodSeconds: 0
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values: ["lethe"]
            topologyKey: kubernetes.io/hostname
      containers:
      - name: devpod
        image: ghcr.io/kuoss/devpod:v0.1.7
        command: ['sh','-c','/root/init.sh']
        workingDir: /ws
        envFrom:
        - configMapRef:
            name: devpod-envs-ini
        resources:
          requests:
            memory: "1000Mi"
            cpu: "100m"
          limits:
            memory: "2000Mi"
            cpu: "1000m"
        volumeMounts:
        - name: vol-init-sh
          mountPath: /root/init.sh
          subPath: init.sh
        - name: vol-ws
          mountPath: /ws
        - name: vol-data
          mountPath: /data
      volumes:
      - name: vol-init-sh
        configMap:
          name: devpod-init-sh
          defaultMode: 0775
      - name: vol-ws
        persistentVolumeClaim:
          claimName: devpod
      - name: vol-data
        persistentVolumeClaim:
          claimName: lethe