---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: devpod
  namespace: kuoss
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: devpod
  namespace: kuoss
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - pods
  - pods/log
  - secrets
  - serviceaccounts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: devpod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: devpod
subjects:
- kind: ServiceAccount
  name: devpod
  namespace: kuoss
