---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: devpod
  namespace: kuoss
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: devpod
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - pods
  - pods/log
  - secrets
  - services
  - serviceaccounts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  - clusterrolebindings
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: devpod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: devpod
subjects:
- kind: ServiceAccount
  name: devpod
  namespace: kuoss
