---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: devpod-ws
  namespace: kuoss
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: devpod-vscode-server
  namespace: kuoss
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
