---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: devpod
  namespace: kuoss
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lethe
  namespace: kuoss
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
