---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: venti
  name: venti-dev
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get","list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: venti-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: venti-dev
subjects:
- kind: ServiceAccount
  name: venti-dev
  namespace: kuoss-dev
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: venti-dev
  namespace: kuoss-dev